//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ConsoleMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ConsoleMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Common.ConsoleMessages", typeof(ConsoleMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning: Coluld not read project logo file. Using default logo of Krypton Report..
        /// </summary>
        public static string COULD_NOT_READ_PROJECT_LOGO {
            get {
                return ResourceManager.GetString("COULD_NOT_READ_PROJECT_LOGO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning: &quot;EmailNotificationFrom&quot; parameter is invalid! Email notification process aborted.
        /// </summary>
        public static string EMAIL_NOTIFICATION_ABORTED {
            get {
                return ResourceManager.GetString("EMAIL_NOTIFICATION_ABORTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning: Email StartTemplate file is missing! Email notification process aborted.
        /// </summary>
        public static string EMAIL_TEMPLETE_MISSING {
            get {
                return ResourceManager.GetString("EMAIL_TEMPLETE_MISSING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception while trying to delete older test runs. Error: .
        /// </summary>
        public static string EXCEPTION_WHILE_DELETING_TEST_RUNS {
            get {
                return ResourceManager.GetString("EXCEPTION_WHILE_DELETING_TEST_RUNS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Not Found:  .
        /// </summary>
        public static string FOD {
            get {
                return ResourceManager.GetString("FOD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KRYPTONPrallelRecovery : invalid arguments.
        /// </summary>
        public static string INVALID_ARGUMNETS {
            get {
                return ResourceManager.GetString("INVALID_ARGUMNETS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ------------------------------------------------.
        /// </summary>
        public static string MSG_DASHED {
            get {
                return ResourceManager.GetString("MSG_DASHED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test Case Execution Completed! Log file generation in Process...
        /// </summary>
        public static string MSG_EXCECUTION_COMPLETE_LOG {
            get {
                return ResourceManager.GetString("MSG_EXCECUTION_COMPLETE_LOG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Execution Completed! HTML Report file generation in Process...
        /// </summary>
        public static string MSG_EXCECUTION_COMPLETED_HTML {
            get {
                return ResourceManager.GetString("MSG_EXCECUTION_COMPLETED_HTML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Execution has been ended from the test case..
        /// </summary>
        public static string MSG_EXCEUTION_ENDS {
            get {
                return ResourceManager.GetString("MSG_EXCEUTION_ENDS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nos. of failure(s) exceeds failed counter..
        /// </summary>
        public static string MSG_FAILURE_EXCEED {
            get {
                return ResourceManager.GetString("MSG_FAILURE_EXCEED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not start parallel recovery...
        /// </summary>
        public static string MSG_PARALLEL_RECOVERY {
            get {
                return ResourceManager.GetString("MSG_PARALLEL_RECOVERY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process Terminates with Exception! Please press [Enter]....
        /// </summary>
        public static string MSG_TERMINATE_WITH_EXCEPTION {
            get {
                return ResourceManager.GetString("MSG_TERMINATE_WITH_EXCEPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uploading log file(s)...
        /// </summary>
        public static string MSG_UPLOADING_LOG {
            get {
                return ResourceManager.GetString("MSG_UPLOADING_LOG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KRYPTONPrallelRecovery : .
        /// </summary>
        public static string PARALLEL_rECOVERY {
            get {
                return ResourceManager.GetString("PARALLEL_rECOVERY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please register AutoIt dll.
        /// </summary>
        public static string REGISTER_AUTOIT {
            get {
                return ResourceManager.GetString("REGISTER_AUTOIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAALwAAAA1CAMAAADMKHGJAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAPBQTFRFAAAAAK7vCT1g////CT1gCT1gCT1gAK7vCT1gAK7vCT1gAK7vCT1gAK7vCT1gAK7vAK7vCT1gAK7vCT1gCT1gAK7vCT1gCT1gAK7vCT1gCT1gAK7vCT1gAK7vAK7vCT1gAK7vAK7vCT1gCT1gCT1gAK7vCT1gAK7vCT1gCT1gAK7vCT1gCT1gAK7vCT1gAK7vCT1gCT1gAK7vCT1gAK7vCT1gCT1gAK7vAK7vCT1gCT1gAK7vCT1gCT1gCT1gAK7vAK7vCT1gCT1gAK7vCT1gCT1gAK7vCT1gCT1gAK7vCT1gCT1gAK7vCT1gAK7vCT1gYRXGaAAAAE50Uk5TAAAAAAMJDBAQEhIeHiAgISotMDA8QEBLUFBUWlpdYGBpcHB1eI [rest of string was truncated]&quot;;.
        /// </summary>
        public static string THINKSYSLOGO {
            get {
                return ResourceManager.GetString("THINKSYSLOGO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web page Fail to Load.
        /// </summary>
        public static string WEB_PAGE_FAILE_LOAD {
            get {
                return ResourceManager.GetString("WEB_PAGE_FAILE_LOAD", resourceCulture);
            }
        }
    }
}
