//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ConsoleMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ConsoleMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Common.ConsoleMessages", typeof(ConsoleMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ------------------------------------------------.
        /// </summary>
        public static string MSG_DASHED {
            get {
                return ResourceManager.GetString("MSG_DASHED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test Case Execution Completed! Log file generation in Process...
        /// </summary>
        public static string MSG_EXCECUTION_COMPLETE_LOG {
            get {
                return ResourceManager.GetString("MSG_EXCECUTION_COMPLETE_LOG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Execution Completed! HTML Report file generation in Process...
        /// </summary>
        public static string MSG_EXCECUTION_COMPLETED_HTML {
            get {
                return ResourceManager.GetString("MSG_EXCECUTION_COMPLETED_HTML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Execution has been ended from the test case..
        /// </summary>
        public static string MSG_EXCEUTION_ENDS {
            get {
                return ResourceManager.GetString("MSG_EXCEUTION_ENDS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nos. of failure(s) exceeds failed counter..
        /// </summary>
        public static string MSG_FAILURE_EXCEED {
            get {
                return ResourceManager.GetString("MSG_FAILURE_EXCEED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not start parallel recovery...
        /// </summary>
        public static string MSG_PARALLEL_RECOVERY {
            get {
                return ResourceManager.GetString("MSG_PARALLEL_RECOVERY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process Terminates with Exception! Please press [Enter]....
        /// </summary>
        public static string MSG_TERMINATE_WITH_EXCEPTION {
            get {
                return ResourceManager.GetString("MSG_TERMINATE_WITH_EXCEPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uploading log file(s)...
        /// </summary>
        public static string MSG_UPLOADING_LOG {
            get {
                return ResourceManager.GetString("MSG_UPLOADING_LOG", resourceCulture);
            }
        }
    }
}
