//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Exceptions {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Exceptions() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Common.Exceptions", typeof(Exceptions).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected error. Error 404: Not Found.
        /// </summary>
        public static string ERROR_404 {
            get {
                return ResourceManager.GetString("ERROR_404", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not start recovery process.
        /// </summary>
        public static string ERROR_AUTOIT {
            get {
                return ResourceManager.GetString("ERROR_AUTOIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while executing test cleanup batch:.
        /// </summary>
        public static string ERROR_CLEANUP {
            get {
                return ResourceManager.GetString("ERROR_CLEANUP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: element is not attached to the page document.
        /// </summary>
        public static string ERROR_ELEMENT_NOT_ATTACHED {
            get {
                return ResourceManager.GetString("ERROR_ELEMENT_NOT_ATTACHED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid command line arguments.Please verify the command line input for Krypton.
        /// </summary>
        public static string ERROR_INVALIDCOMMANDLINE {
            get {
                return ResourceManager.GetString("ERROR_INVALIDCOMMANDLINE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Test Case Id:.
        /// </summary>
        public static string ERROR_INVALIDTESTID {
            get {
                return ResourceManager.GetString("ERROR_INVALIDTESTID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No response from server for url.
        /// </summary>
        public static string ERROR_NORESPONSEURL {
            get {
                return ResourceManager.GetString("ERROR_NORESPONSEURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Krypton could not locate even a single test case for test suite and filter criteria specified..
        /// </summary>
        public static string ERROR_NOTESTCASEFOUND {
            get {
                return ResourceManager.GetString("ERROR_NOTESTCASEFOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not found object with with property:.
        /// </summary>
        public static string ERROR_OBJECTNOTFOUND {
            get {
                return ResourceManager.GetString("ERROR_OBJECTNOTFOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No entry found for columns in Object Repository file.
        /// </summary>
        public static string ERROR_OBJECTREPOSITORY {
            get {
                return ResourceManager.GetString("ERROR_OBJECTREPOSITORY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected character encountered while parsing value.
        /// </summary>
        public static string ERROR_PARSINGVALUE {
            get {
                return ResourceManager.GetString("ERROR_PARSINGVALUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please run autoit-v3-setup.
        /// </summary>
        public static string ERROR_RECOVERY {
            get {
                return ResourceManager.GetString("ERROR_RECOVERY", resourceCulture);
            }
        }
    }
}
